### ISSUE TITLE
'.' is not recognized as an internal or external command, on PRODUCTION

### ISSUE THREAD

**Issue by guruprasaad123** [YaleDHLab/flask-react-boilerplate#2] opened 2019-05-04 04:49 UTC
I tried to issue the command for production in `windows`
`npm run production`

and i have been getting this weird problem.
```
> npm run build && npm run serve


> let-them-speak@0.1.0 build D:\workspace\@react\#onet\flask-react-boilerplate
> ./node_modules/webpack/bin/webpack.js --config webpack.config.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! let-them-speak@0.1.0 build: `./node_modules/webpack/bin/webpack.js --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the let-them-speak@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by duhaime** [comment] 2019-05-04 12:58
Hmm that's curious @guruprasaad123. What's your Node version? You should be able to check with `node -v`.

I would install the Node version manager if you don't have it already (it will be helpful as the Node runtime continues to evolve), then I'd install a recent version of Node. Once that's set I'd repeat all the steps in the readme to get the boilerplate dependencies installed.

Could you try that and let me know how it goes? If you get stuck again I'm happy to help--we just need to figure out how I can reproduce this problem, as I can't do so just yet...

**Comment by guruprasaad123** [comment] 2019-05-10 06:39
node version = 8

**Comment by duhaime** [comment] 2019-05-10 12:10
Ah sorry @guruprasaad123 I think this issue is caused by the fact that you're on windows and the binary evocations should look a little different on that OS.

To test that hypothesis, can I please ask you to try a:

```
git pull origin master
npm install --no-optional
npm start
```

I've just pushed some changes that remove the explicit binary paths from the npm scripts, which should resolve this. If you could give that a go and let me know the outcome I'd be grateful!

**Comment by guruprasaad123** [comment] 2019-05-13 06:01
yeah sure bro i'll try and let you know 
! cheers

**Comment by duhaime** [comment] 2019-07-15 15:25
@guruprasaad123 have you had a chance to look into this by chance? If so, could I ask you how the updated master is treating you? If this is resolved, I'd be grateful if you could close this issue out!

**Closed** 2019-08-20 13:43 UTC
